<?xml version="1.0" encoding="utf-8"?><testsuite errors="2" failures="1" name="pytest" skips="0" tests="4" time="0.789"><testcase classname="nbexchange.tests.test_dbutil" file="nbexchange/tests/test_dbutil.py" line="3" name="test_dbutil" time="0.0011115074157714844"><system-out>Select a command from: alembic
</system-out></testcase><testcase classname="nbexchange.tests.test_handlers" file="nbexchange/tests/test_handlers.py" line="6" name="test_main_page" time="0.02768850326538086"><error message="test setup failure">request = &lt;SubRequest &apos;app&apos; for &lt;Function &apos;test_main_page&apos;&gt;&gt;, io_loop = &lt;tornado.platform.asyncio.AsyncIOLoop object at 0x7f78d6de0ba8&gt;
_nbexchange_config = {&apos;NbExchange&apos;: {&apos;hub_base_url&apos;: &lt;traitlets.config.loader.LazyConfigValue object at 0x7f78d6de0a58&gt;, &apos;hub_url&apos;: &apos;&apos;}}

    @pytest.fixture
    def app(request, io_loop, _nbexchange_config):
        &quot;&quot;&quot;Launch the NbExchange app
        &quot;&quot;&quot;
        nbexchange = NbExchange.instance(config=_nbexchange_config)
&gt;       nbexchange.initialize([])

nbexchange/tests/conftest.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/traitlets/config/application.py:87: in catch_config_error
    return method(app, *args, **kwargs)
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/app.py:242: in initialize
    self.init_db()
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/app.py:159: in init_db
    **self.db_kwargs
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/orm.py:502: in new_session_factory
    check_db_revision(engine, log)
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/orm.py:424: in check_db_revision
    with _temp_alembic_ini(engine.url) as ini:
../../../.pyenv/versions/3.6.6/lib/python3.6/contextlib.py:81: in __enter__
    return next(self.gen)
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/dbutil.py:70: in _temp_alembic_ini
    write_alembic_ini(alembic_ini, db_url)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

alembic_ini = &apos;/tmp/tmp8xe26cw6/alembic.ini&apos;, db_url = sqlite:///nbexchange.sqlite

    def write_alembic_ini(alembic_ini=&quot;alembic.ini&quot;, db_url=&quot;sqlite:///nbexchange.sqlite&quot;):
        &quot;&quot;&quot;Write a complete alembic.ini from our template.
    
        Parameters
        ----------
    
        alembic_ini: str
            path to the alembic.ini file that should be written.
        db_url: str
            The SQLAlchemy database url, e.g. `sqlite:///nbexchange.sqlite`.
        &quot;&quot;&quot;
&gt;       with open(ALEMBIC_INI_TEMPLATE_PATH) as f:
E       FileNotFoundError: [Errno 2] No such file or directory: &apos;/home/brobbere/.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/alembic.ini&apos;

../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/dbutil.py:31: FileNotFoundError</error><system-out>JupyterHub not available at &lt;traitlets.config.loader.LazyConfigValue object at 0x7f78d6de0a58&gt;: Invalid URL &apos;&lt;traitlets.config.loader.LazyConfigValue object at 0x7f78d6de0a58&gt;&apos;: No schema supplied. Perhaps you meant http://&lt;traitlets.config.loader.LazyConfigValue object at 0x7f78d6de0a58&gt;?
</system-out><system-err>[W 2018-11-15 13:45:37.231 NbExchange configurable:168] Config option `hub_url` not recognized by `NbExchange`.  Did you mean one of: `db_url, hub_api_url, hub_base_url`?
[W 2018-11-15 13:45:37.234 NbExchange configurable:168] Config option `hub_url` not recognized by `NbExchange`.  Did you mean one of: `db_url, hub_api_url, hub_base_url`?
[I 2018-11-15 13:45:37.234 NbExchange orm:477] orm.new_session_factory: db_url:sqlite:///nbexchange.sqlite, reset:False
[I 2018-11-15 13:45:37.246 NbExchange orm:492] orm.new_session_factory: engine:Engine(sqlite:///nbexchange.sqlite)
</system-err></testcase><testcase classname="nbexchange.tests.test_handlers" file="nbexchange/tests/test_handlers.py" line="15" name="test_user_endpoint" time="0.00629878044128418"><error message="test setup failure">request = &lt;SubRequest &apos;app&apos; for &lt;Function &apos;test_user_endpoint&apos;&gt;&gt;, io_loop = &lt;tornado.platform.asyncio.AsyncIOLoop object at 0x7f78d67705c0&gt;
_nbexchange_config = {&apos;NbExchange&apos;: {&apos;hub_base_url&apos;: &lt;traitlets.config.loader.LazyConfigValue object at 0x7f78d6de0a58&gt;, &apos;hub_url&apos;: &apos;&apos;}}

    @pytest.fixture
    def app(request, io_loop, _nbexchange_config):
        &quot;&quot;&quot;Launch the NbExchange app
        &quot;&quot;&quot;
        nbexchange = NbExchange.instance(config=_nbexchange_config)
&gt;       nbexchange.initialize([])

nbexchange/tests/conftest.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/traitlets/config/application.py:87: in catch_config_error
    return method(app, *args, **kwargs)
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/app.py:242: in initialize
    self.init_db()
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/app.py:159: in init_db
    **self.db_kwargs
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/orm.py:502: in new_session_factory
    check_db_revision(engine, log)
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/orm.py:424: in check_db_revision
    with _temp_alembic_ini(engine.url) as ini:
../../../.pyenv/versions/3.6.6/lib/python3.6/contextlib.py:81: in __enter__
    return next(self.gen)
../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/dbutil.py:70: in _temp_alembic_ini
    write_alembic_ini(alembic_ini, db_url)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

alembic_ini = &apos;/tmp/tmpvvvpcu29/alembic.ini&apos;, db_url = sqlite:///nbexchange.sqlite

    def write_alembic_ini(alembic_ini=&quot;alembic.ini&quot;, db_url=&quot;sqlite:///nbexchange.sqlite&quot;):
        &quot;&quot;&quot;Write a complete alembic.ini from our template.
    
        Parameters
        ----------
    
        alembic_ini: str
            path to the alembic.ini file that should be written.
        db_url: str
            The SQLAlchemy database url, e.g. `sqlite:///nbexchange.sqlite`.
        &quot;&quot;&quot;
&gt;       with open(ALEMBIC_INI_TEMPLATE_PATH) as f:
E       FileNotFoundError: [Errno 2] No such file or directory: &apos;/home/brobbere/.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/alembic.ini&apos;

../../../.pyenv/versions/3.6.6/envs/nexchange/lib/python3.6/site-packages/nbexchange/dbutil.py:31: FileNotFoundError</error><system-err>[W 2018-11-15 13:45:37.401 NbExchange configurable:168] Config option `hub_url` not recognized by `NbExchange`.  Did you mean one of: `db_url, hub_api_url, hub_base_url`?
[I 2018-11-15 13:45:37.402 NbExchange orm:477] orm.new_session_factory: db_url:sqlite:///nbexchange.sqlite, reset:False
[I 2018-11-15 13:45:37.403 NbExchange orm:492] orm.new_session_factory: engine:Engine(sqlite:///nbexchange.sqlite)
</system-err></testcase><testcase classname="nbexchange.tests.test_something" file="nbexchange/tests/test_something.py" line="3" name="test_this" time="0.0012881755828857422"><failure message="AssertionError: assert &apos;Hello&apos; == &apos;Goodbye&apos;
  - Hello
  + Goodbye">def test_this():
&gt;       assert &quot;Hello&quot; == &quot;Goodbye&quot;
E       AssertionError: assert &apos;Hello&apos; == &apos;Goodbye&apos;
E         - Hello
E         + Goodbye

nbexchange/tests/test_something.py:5: AssertionError</failure></testcase></testsuite>